version: '3'
services:
  neo4j:
    image: neo4j:3.5.23
    hostname: Rhushikeshs-iMac.local
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./plugins:/plugins
      - ./conf:/config
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
   
  